/* Firebase Messaging Service Worker (generated by Laravel) */

/* eslint-disable no-undef */
// Use a version that exists on the Firebase CDN (see https://firebase.google.com/docs/cloud-messaging/js/receive)
importScripts('https://www.gstatic.com/firebasejs/10.13.2/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.13.2/firebase-messaging-compat.js');

// Config is injected from server env.
const firebaseConfig = {!! $firebaseConfigJson !!};

try {
    if (firebaseConfig && firebaseConfig.apiKey) {
        firebase.initializeApp(firebaseConfig);
        const messaging = firebase.messaging();

        // Show notifications when app is in background.
        messaging.onBackgroundMessage(function (payload) {
            const title = payload?.notification?.title || 'Notification';
            const options = {
                body: payload?.notification?.body || '',
                data: payload?.data || {},
            };
            self.registration.showNotification(title, options);
        });

        // Handle click: open url if provided.
        self.addEventListener('notificationclick', function (event) {
            event.notification.close();
            const url = event?.notification?.data?.url;
            if (!url) return;
            event.waitUntil(clients.openWindow(url));
        });
    }
} catch (e) {
    // no-op
}

